export class Campus_name {
  name!: string[]; //Campus_name
}

// Generated by https://quicktype.io

export interface campus_request {
  campus: string;
}

// Generated by https://quicktype.io

export interface Test {
  restaurant_id: string;
  restaurant_type: string;
  restaurant_name: string;
  image_url: string;
}
