export class Food {
  item_id!: string; //item_id
  item_name!: string; //item_name
  price!: number; //price
  category!: string; //category
  //stars!: number; //star_rating
  image_url!: string; //image_url
  restaurant_id!: string; //restaurant_id
  description!: string; //description
  availibility!: boolean; //availibility
  restaurant_name!: string; //restaurant_name
  restaurant_type!: string;
}
// Generated by https://quicktype.io

export interface FoodRes {
  item_id: string;
  restaurant_id: string;
  restaurant_type: string;
  restaurant_name: string;
  category: string;
  item_name: string;
  description: string;
  price: number;
  availability: boolean;
  image_url: string;
  star_rating: null;
}

// Generated by https://quicktype.io

export interface MenuInfo {
  role: string;
  restaurant_id: string;
}
